// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj2iInY9Isa24w-LFFtTEcz2kO9ZiaIy8',
    appId: '1:259602366484:web:3c24e77a2422e37f4fa701',
    messagingSenderId: '259602366484',
    projectId: 'ecommerapp-6c040',
    authDomain: 'ecommerapp-6c040.firebaseapp.com',
    storageBucket: 'ecommerapp-6c040.firebasestorage.app',
    measurementId: 'G-E5MTMN3GF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAd1jldTV4CwrgorDLN8Z6OBpDr56hPsU',
    appId: '1:259602366484:android:917282a2679faa944fa701',
    messagingSenderId: '259602366484',
    projectId: 'ecommerapp-6c040',
    storageBucket: 'ecommerapp-6c040.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR5IV3rfphOFnxt0bwgFOCNtmjX4FGJdk',
    appId: '1:259602366484:ios:07427b5a3de138f54fa701',
    messagingSenderId: '259602366484',
    projectId: 'ecommerapp-6c040',
    storageBucket: 'ecommerapp-6c040.firebasestorage.app',
    iosBundleId: 'com.example.livraisonb2b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR5IV3rfphOFnxt0bwgFOCNtmjX4FGJdk',
    appId: '1:259602366484:ios:07427b5a3de138f54fa701',
    messagingSenderId: '259602366484',
    projectId: 'ecommerapp-6c040',
    storageBucket: 'ecommerapp-6c040.firebasestorage.app',
    iosBundleId: 'com.example.livraisonb2b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj2iInY9Isa24w-LFFtTEcz2kO9ZiaIy8',
    appId: '1:259602366484:web:46811fbc26e5108d4fa701',
    messagingSenderId: '259602366484',
    projectId: 'ecommerapp-6c040',
    authDomain: 'ecommerapp-6c040.firebaseapp.com',
    storageBucket: 'ecommerapp-6c040.firebasestorage.app',
    measurementId: 'G-RH6D87REFD',
  );
}
